// source: payload.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.SimObjData', null, global);
goog.exportSymbol('proto.SimUpdate', null, global);
goog.exportSymbol('proto.SolarObj', null, global);
goog.exportSymbol('proto.SolarObjData', null, global);
goog.exportSymbol('proto.Vec3D', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Vec3D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Vec3D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Vec3D.displayName = 'proto.Vec3D';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SolarObjData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SolarObjData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SolarObjData.displayName = 'proto.SolarObjData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SimObjData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SimObjData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SimObjData.displayName = 'proto.SimObjData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SimUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SimUpdate.repeatedFields_, null);
};
goog.inherits(proto.SimUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SimUpdate.displayName = 'proto.SimUpdate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Vec3D.prototype.toObject = function(opt_includeInstance) {
  return proto.Vec3D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Vec3D} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Vec3D.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    z: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Vec3D}
 */
proto.Vec3D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Vec3D;
  return proto.Vec3D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Vec3D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Vec3D}
 */
proto.Vec3D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Vec3D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Vec3D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Vec3D} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Vec3D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getZ();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional double x = 1;
 * @return {number}
 */
proto.Vec3D.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Vec3D} returns this
 */
proto.Vec3D.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double y = 2;
 * @return {number}
 */
proto.Vec3D.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Vec3D} returns this
 */
proto.Vec3D.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double z = 3;
 * @return {number}
 */
proto.Vec3D.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Vec3D} returns this
 */
proto.Vec3D.prototype.setZ = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SolarObjData.prototype.toObject = function(opt_includeInstance) {
  return proto.SolarObjData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SolarObjData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SolarObjData.toObject = function(includeInstance, msg) {
  var f, obj = {
    solarObj: jspb.Message.getFieldWithDefault(msg, 1, 0),
    absCoord: (f = msg.getAbsCoord()) && proto.Vec3D.toObject(includeInstance, f),
    velocity: (f = msg.getVelocity()) && proto.Vec3D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SolarObjData}
 */
proto.SolarObjData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SolarObjData;
  return proto.SolarObjData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SolarObjData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SolarObjData}
 */
proto.SolarObjData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.SolarObj} */ (reader.readEnum());
      msg.setSolarObj(value);
      break;
    case 2:
      var value = new proto.Vec3D;
      reader.readMessage(value,proto.Vec3D.deserializeBinaryFromReader);
      msg.setAbsCoord(value);
      break;
    case 3:
      var value = new proto.Vec3D;
      reader.readMessage(value,proto.Vec3D.deserializeBinaryFromReader);
      msg.setVelocity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SolarObjData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SolarObjData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SolarObjData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SolarObjData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSolarObj();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAbsCoord();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Vec3D.serializeBinaryToWriter
    );
  }
  f = message.getVelocity();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Vec3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional SolarObj solar_obj = 1;
 * @return {!proto.SolarObj}
 */
proto.SolarObjData.prototype.getSolarObj = function() {
  return /** @type {!proto.SolarObj} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.SolarObj} value
 * @return {!proto.SolarObjData} returns this
 */
proto.SolarObjData.prototype.setSolarObj = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Vec3D abs_coord = 2;
 * @return {?proto.Vec3D}
 */
proto.SolarObjData.prototype.getAbsCoord = function() {
  return /** @type{?proto.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.Vec3D, 2));
};


/**
 * @param {?proto.Vec3D|undefined} value
 * @return {!proto.SolarObjData} returns this
*/
proto.SolarObjData.prototype.setAbsCoord = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SolarObjData} returns this
 */
proto.SolarObjData.prototype.clearAbsCoord = function() {
  return this.setAbsCoord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SolarObjData.prototype.hasAbsCoord = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Vec3D velocity = 3;
 * @return {?proto.Vec3D}
 */
proto.SolarObjData.prototype.getVelocity = function() {
  return /** @type{?proto.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.Vec3D, 3));
};


/**
 * @param {?proto.Vec3D|undefined} value
 * @return {!proto.SolarObjData} returns this
*/
proto.SolarObjData.prototype.setVelocity = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SolarObjData} returns this
 */
proto.SolarObjData.prototype.clearVelocity = function() {
  return this.setVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SolarObjData.prototype.hasVelocity = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SimObjData.prototype.toObject = function(opt_includeInstance) {
  return proto.SimObjData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SimObjData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SimObjData.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    soi: jspb.Message.getFieldWithDefault(msg, 2, 0),
    absCoord: (f = msg.getAbsCoord()) && proto.Vec3D.toObject(includeInstance, f),
    velocity: (f = msg.getVelocity()) && proto.Vec3D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SimObjData}
 */
proto.SimObjData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SimObjData;
  return proto.SimObjData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SimObjData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SimObjData}
 */
proto.SimObjData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.SolarObj} */ (reader.readEnum());
      msg.setSoi(value);
      break;
    case 3:
      var value = new proto.Vec3D;
      reader.readMessage(value,proto.Vec3D.deserializeBinaryFromReader);
      msg.setAbsCoord(value);
      break;
    case 4:
      var value = new proto.Vec3D;
      reader.readMessage(value,proto.Vec3D.deserializeBinaryFromReader);
      msg.setVelocity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SimObjData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SimObjData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SimObjData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SimObjData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getSoi();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getAbsCoord();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Vec3D.serializeBinaryToWriter
    );
  }
  f = message.getVelocity();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.Vec3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.SimObjData.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.SimObjData} returns this
 */
proto.SimObjData.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional SolarObj soi = 2;
 * @return {!proto.SolarObj}
 */
proto.SimObjData.prototype.getSoi = function() {
  return /** @type {!proto.SolarObj} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.SolarObj} value
 * @return {!proto.SimObjData} returns this
 */
proto.SimObjData.prototype.setSoi = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Vec3D abs_coord = 3;
 * @return {?proto.Vec3D}
 */
proto.SimObjData.prototype.getAbsCoord = function() {
  return /** @type{?proto.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.Vec3D, 3));
};


/**
 * @param {?proto.Vec3D|undefined} value
 * @return {!proto.SimObjData} returns this
*/
proto.SimObjData.prototype.setAbsCoord = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SimObjData} returns this
 */
proto.SimObjData.prototype.clearAbsCoord = function() {
  return this.setAbsCoord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SimObjData.prototype.hasAbsCoord = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Vec3D velocity = 4;
 * @return {?proto.Vec3D}
 */
proto.SimObjData.prototype.getVelocity = function() {
  return /** @type{?proto.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.Vec3D, 4));
};


/**
 * @param {?proto.Vec3D|undefined} value
 * @return {!proto.SimObjData} returns this
*/
proto.SimObjData.prototype.setVelocity = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SimObjData} returns this
 */
proto.SimObjData.prototype.clearVelocity = function() {
  return this.setVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SimObjData.prototype.hasVelocity = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SimUpdate.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SimUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.SimUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SimUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SimUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    simTime: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    solarObjUpdateList: jspb.Message.toObjectList(msg.getSolarObjUpdateList(),
    proto.SolarObjData.toObject, includeInstance),
    simObjUpdateList: jspb.Message.toObjectList(msg.getSimObjUpdateList(),
    proto.SimObjData.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SimUpdate}
 */
proto.SimUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SimUpdate;
  return proto.SimUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SimUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SimUpdate}
 */
proto.SimUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSimTime(value);
      break;
    case 2:
      var value = new proto.SolarObjData;
      reader.readMessage(value,proto.SolarObjData.deserializeBinaryFromReader);
      msg.addSolarObjUpdate(value);
      break;
    case 3:
      var value = new proto.SimObjData;
      reader.readMessage(value,proto.SimObjData.deserializeBinaryFromReader);
      msg.addSimObjUpdate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SimUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SimUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SimUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SimUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSimTime();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getSolarObjUpdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.SolarObjData.serializeBinaryToWriter
    );
  }
  f = message.getSimObjUpdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.SimObjData.serializeBinaryToWriter
    );
  }
};


/**
 * optional double sim_time = 1;
 * @return {number}
 */
proto.SimUpdate.prototype.getSimTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SimUpdate} returns this
 */
proto.SimUpdate.prototype.setSimTime = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * repeated SolarObjData solar_obj_update = 2;
 * @return {!Array<!proto.SolarObjData>}
 */
proto.SimUpdate.prototype.getSolarObjUpdateList = function() {
  return /** @type{!Array<!proto.SolarObjData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SolarObjData, 2));
};


/**
 * @param {!Array<!proto.SolarObjData>} value
 * @return {!proto.SimUpdate} returns this
*/
proto.SimUpdate.prototype.setSolarObjUpdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SolarObjData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SolarObjData}
 */
proto.SimUpdate.prototype.addSolarObjUpdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SolarObjData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SimUpdate} returns this
 */
proto.SimUpdate.prototype.clearSolarObjUpdateList = function() {
  return this.setSolarObjUpdateList([]);
};


/**
 * repeated SimObjData sim_obj_update = 3;
 * @return {!Array<!proto.SimObjData>}
 */
proto.SimUpdate.prototype.getSimObjUpdateList = function() {
  return /** @type{!Array<!proto.SimObjData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SimObjData, 3));
};


/**
 * @param {!Array<!proto.SimObjData>} value
 * @return {!proto.SimUpdate} returns this
*/
proto.SimUpdate.prototype.setSimObjUpdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.SimObjData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SimObjData}
 */
proto.SimUpdate.prototype.addSimObjUpdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.SimObjData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SimUpdate} returns this
 */
proto.SimUpdate.prototype.clearSimObjUpdateList = function() {
  return this.setSimObjUpdateList([]);
};


/**
 * @enum {number}
 */
proto.SolarObj = {
  SUN: 0,
  EARTH: 1,
  MOON: 2
};

goog.object.extend(exports, proto);
