// source: sim.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sim.SimDataRequest', null, global);
goog.exportSymbol('proto.sim.SimObjData', null, global);
goog.exportSymbol('proto.sim.SimObjRequest', null, global);
goog.exportSymbol('proto.sim.SimRequest', null, global);
goog.exportSymbol('proto.sim.SimRequest.RequestCase', null, global);
goog.exportSymbol('proto.sim.SimUpdate', null, global);
goog.exportSymbol('proto.sim.SolarObj', null, global);
goog.exportSymbol('proto.sim.SolarObjData', null, global);
goog.exportSymbol('proto.sim.Vec3D', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sim.Vec3D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sim.Vec3D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sim.Vec3D.displayName = 'proto.sim.Vec3D';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sim.SolarObjData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sim.SolarObjData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sim.SolarObjData.displayName = 'proto.sim.SolarObjData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sim.SimObjData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sim.SimObjData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sim.SimObjData.displayName = 'proto.sim.SimObjData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sim.SimUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sim.SimUpdate.repeatedFields_, null);
};
goog.inherits(proto.sim.SimUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sim.SimUpdate.displayName = 'proto.sim.SimUpdate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sim.SimObjRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sim.SimObjRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sim.SimObjRequest.displayName = 'proto.sim.SimObjRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sim.SimDataRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sim.SimDataRequest.repeatedFields_, null);
};
goog.inherits(proto.sim.SimDataRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sim.SimDataRequest.displayName = 'proto.sim.SimDataRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sim.SimRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sim.SimRequest.oneofGroups_);
};
goog.inherits(proto.sim.SimRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sim.SimRequest.displayName = 'proto.sim.SimRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sim.Vec3D.prototype.toObject = function(opt_includeInstance) {
  return proto.sim.Vec3D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sim.Vec3D} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.Vec3D.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    z: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sim.Vec3D}
 */
proto.sim.Vec3D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sim.Vec3D;
  return proto.sim.Vec3D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sim.Vec3D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sim.Vec3D}
 */
proto.sim.Vec3D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sim.Vec3D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sim.Vec3D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sim.Vec3D} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.Vec3D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getZ();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional double x = 1;
 * @return {number}
 */
proto.sim.Vec3D.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sim.Vec3D} returns this
 */
proto.sim.Vec3D.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double y = 2;
 * @return {number}
 */
proto.sim.Vec3D.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sim.Vec3D} returns this
 */
proto.sim.Vec3D.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double z = 3;
 * @return {number}
 */
proto.sim.Vec3D.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sim.Vec3D} returns this
 */
proto.sim.Vec3D.prototype.setZ = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sim.SolarObjData.prototype.toObject = function(opt_includeInstance) {
  return proto.sim.SolarObjData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sim.SolarObjData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SolarObjData.toObject = function(includeInstance, msg) {
  var f, obj = {
    solarObj: jspb.Message.getFieldWithDefault(msg, 1, 0),
    absCoord: (f = msg.getAbsCoord()) && proto.sim.Vec3D.toObject(includeInstance, f),
    velocity: (f = msg.getVelocity()) && proto.sim.Vec3D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sim.SolarObjData}
 */
proto.sim.SolarObjData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sim.SolarObjData;
  return proto.sim.SolarObjData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sim.SolarObjData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sim.SolarObjData}
 */
proto.sim.SolarObjData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sim.SolarObj} */ (reader.readEnum());
      msg.setSolarObj(value);
      break;
    case 2:
      var value = new proto.sim.Vec3D;
      reader.readMessage(value,proto.sim.Vec3D.deserializeBinaryFromReader);
      msg.setAbsCoord(value);
      break;
    case 3:
      var value = new proto.sim.Vec3D;
      reader.readMessage(value,proto.sim.Vec3D.deserializeBinaryFromReader);
      msg.setVelocity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sim.SolarObjData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sim.SolarObjData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sim.SolarObjData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SolarObjData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSolarObj();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAbsCoord();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sim.Vec3D.serializeBinaryToWriter
    );
  }
  f = message.getVelocity();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sim.Vec3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional SolarObj solar_obj = 1;
 * @return {!proto.sim.SolarObj}
 */
proto.sim.SolarObjData.prototype.getSolarObj = function() {
  return /** @type {!proto.sim.SolarObj} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sim.SolarObj} value
 * @return {!proto.sim.SolarObjData} returns this
 */
proto.sim.SolarObjData.prototype.setSolarObj = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Vec3D abs_coord = 2;
 * @return {?proto.sim.Vec3D}
 */
proto.sim.SolarObjData.prototype.getAbsCoord = function() {
  return /** @type{?proto.sim.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.sim.Vec3D, 2));
};


/**
 * @param {?proto.sim.Vec3D|undefined} value
 * @return {!proto.sim.SolarObjData} returns this
*/
proto.sim.SolarObjData.prototype.setAbsCoord = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sim.SolarObjData} returns this
 */
proto.sim.SolarObjData.prototype.clearAbsCoord = function() {
  return this.setAbsCoord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sim.SolarObjData.prototype.hasAbsCoord = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Vec3D velocity = 3;
 * @return {?proto.sim.Vec3D}
 */
proto.sim.SolarObjData.prototype.getVelocity = function() {
  return /** @type{?proto.sim.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.sim.Vec3D, 3));
};


/**
 * @param {?proto.sim.Vec3D|undefined} value
 * @return {!proto.sim.SolarObjData} returns this
*/
proto.sim.SolarObjData.prototype.setVelocity = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sim.SolarObjData} returns this
 */
proto.sim.SolarObjData.prototype.clearVelocity = function() {
  return this.setVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sim.SolarObjData.prototype.hasVelocity = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sim.SimObjData.prototype.toObject = function(opt_includeInstance) {
  return proto.sim.SimObjData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sim.SimObjData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimObjData.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    soi: jspb.Message.getFieldWithDefault(msg, 2, 0),
    absCoord: (f = msg.getAbsCoord()) && proto.sim.Vec3D.toObject(includeInstance, f),
    velocity: (f = msg.getVelocity()) && proto.sim.Vec3D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sim.SimObjData}
 */
proto.sim.SimObjData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sim.SimObjData;
  return proto.sim.SimObjData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sim.SimObjData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sim.SimObjData}
 */
proto.sim.SimObjData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.sim.SolarObj} */ (reader.readEnum());
      msg.setSoi(value);
      break;
    case 3:
      var value = new proto.sim.Vec3D;
      reader.readMessage(value,proto.sim.Vec3D.deserializeBinaryFromReader);
      msg.setAbsCoord(value);
      break;
    case 4:
      var value = new proto.sim.Vec3D;
      reader.readMessage(value,proto.sim.Vec3D.deserializeBinaryFromReader);
      msg.setVelocity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sim.SimObjData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sim.SimObjData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sim.SimObjData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimObjData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getSoi();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getAbsCoord();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sim.Vec3D.serializeBinaryToWriter
    );
  }
  f = message.getVelocity();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sim.Vec3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.sim.SimObjData.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sim.SimObjData} returns this
 */
proto.sim.SimObjData.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional SolarObj soi = 2;
 * @return {!proto.sim.SolarObj}
 */
proto.sim.SimObjData.prototype.getSoi = function() {
  return /** @type {!proto.sim.SolarObj} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sim.SolarObj} value
 * @return {!proto.sim.SimObjData} returns this
 */
proto.sim.SimObjData.prototype.setSoi = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Vec3D abs_coord = 3;
 * @return {?proto.sim.Vec3D}
 */
proto.sim.SimObjData.prototype.getAbsCoord = function() {
  return /** @type{?proto.sim.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.sim.Vec3D, 3));
};


/**
 * @param {?proto.sim.Vec3D|undefined} value
 * @return {!proto.sim.SimObjData} returns this
*/
proto.sim.SimObjData.prototype.setAbsCoord = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sim.SimObjData} returns this
 */
proto.sim.SimObjData.prototype.clearAbsCoord = function() {
  return this.setAbsCoord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sim.SimObjData.prototype.hasAbsCoord = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Vec3D velocity = 4;
 * @return {?proto.sim.Vec3D}
 */
proto.sim.SimObjData.prototype.getVelocity = function() {
  return /** @type{?proto.sim.Vec3D} */ (
    jspb.Message.getWrapperField(this, proto.sim.Vec3D, 4));
};


/**
 * @param {?proto.sim.Vec3D|undefined} value
 * @return {!proto.sim.SimObjData} returns this
*/
proto.sim.SimObjData.prototype.setVelocity = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sim.SimObjData} returns this
 */
proto.sim.SimObjData.prototype.clearVelocity = function() {
  return this.setVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sim.SimObjData.prototype.hasVelocity = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sim.SimUpdate.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sim.SimUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.sim.SimUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sim.SimUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    simTime: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    solarObjUpdateList: jspb.Message.toObjectList(msg.getSolarObjUpdateList(),
    proto.sim.SolarObjData.toObject, includeInstance),
    simObjUpdateList: jspb.Message.toObjectList(msg.getSimObjUpdateList(),
    proto.sim.SimObjData.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sim.SimUpdate}
 */
proto.sim.SimUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sim.SimUpdate;
  return proto.sim.SimUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sim.SimUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sim.SimUpdate}
 */
proto.sim.SimUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSimTime(value);
      break;
    case 2:
      var value = new proto.sim.SolarObjData;
      reader.readMessage(value,proto.sim.SolarObjData.deserializeBinaryFromReader);
      msg.addSolarObjUpdate(value);
      break;
    case 3:
      var value = new proto.sim.SimObjData;
      reader.readMessage(value,proto.sim.SimObjData.deserializeBinaryFromReader);
      msg.addSimObjUpdate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sim.SimUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sim.SimUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sim.SimUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSimTime();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getSolarObjUpdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sim.SolarObjData.serializeBinaryToWriter
    );
  }
  f = message.getSimObjUpdateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.sim.SimObjData.serializeBinaryToWriter
    );
  }
};


/**
 * optional double sim_time = 1;
 * @return {number}
 */
proto.sim.SimUpdate.prototype.getSimTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sim.SimUpdate} returns this
 */
proto.sim.SimUpdate.prototype.setSimTime = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * repeated SolarObjData solar_obj_update = 2;
 * @return {!Array<!proto.sim.SolarObjData>}
 */
proto.sim.SimUpdate.prototype.getSolarObjUpdateList = function() {
  return /** @type{!Array<!proto.sim.SolarObjData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sim.SolarObjData, 2));
};


/**
 * @param {!Array<!proto.sim.SolarObjData>} value
 * @return {!proto.sim.SimUpdate} returns this
*/
proto.sim.SimUpdate.prototype.setSolarObjUpdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sim.SolarObjData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sim.SolarObjData}
 */
proto.sim.SimUpdate.prototype.addSolarObjUpdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sim.SolarObjData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sim.SimUpdate} returns this
 */
proto.sim.SimUpdate.prototype.clearSolarObjUpdateList = function() {
  return this.setSolarObjUpdateList([]);
};


/**
 * repeated SimObjData sim_obj_update = 3;
 * @return {!Array<!proto.sim.SimObjData>}
 */
proto.sim.SimUpdate.prototype.getSimObjUpdateList = function() {
  return /** @type{!Array<!proto.sim.SimObjData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sim.SimObjData, 3));
};


/**
 * @param {!Array<!proto.sim.SimObjData>} value
 * @return {!proto.sim.SimUpdate} returns this
*/
proto.sim.SimUpdate.prototype.setSimObjUpdateList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.sim.SimObjData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sim.SimObjData}
 */
proto.sim.SimUpdate.prototype.addSimObjUpdate = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.sim.SimObjData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sim.SimUpdate} returns this
 */
proto.sim.SimUpdate.prototype.clearSimObjUpdateList = function() {
  return this.setSimObjUpdateList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sim.SimObjRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.sim.SimObjRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sim.SimObjRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimObjRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sendVelocity: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sim.SimObjRequest}
 */
proto.sim.SimObjRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sim.SimObjRequest;
  return proto.sim.SimObjRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sim.SimObjRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sim.SimObjRequest}
 */
proto.sim.SimObjRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSendVelocity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sim.SimObjRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sim.SimObjRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sim.SimObjRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimObjRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getSendVelocity();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.sim.SimObjRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sim.SimObjRequest} returns this
 */
proto.sim.SimObjRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool send_velocity = 2;
 * @return {boolean}
 */
proto.sim.SimObjRequest.prototype.getSendVelocity = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sim.SimObjRequest} returns this
 */
proto.sim.SimObjRequest.prototype.setSendVelocity = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sim.SimDataRequest.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sim.SimDataRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.sim.SimDataRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sim.SimDataRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimDataRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    simTimeStart: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    simTimeEnd: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    sendDensityChunks: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    simObjIdsList: jspb.Message.toObjectList(msg.getSimObjIdsList(),
    proto.sim.SimObjRequest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sim.SimDataRequest}
 */
proto.sim.SimDataRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sim.SimDataRequest;
  return proto.sim.SimDataRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sim.SimDataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sim.SimDataRequest}
 */
proto.sim.SimDataRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSimTimeStart(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSimTimeEnd(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSendDensityChunks(value);
      break;
    case 4:
      var value = new proto.sim.SimObjRequest;
      reader.readMessage(value,proto.sim.SimObjRequest.deserializeBinaryFromReader);
      msg.addSimObjIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sim.SimDataRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sim.SimDataRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sim.SimDataRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimDataRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSimTimeStart();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getSimTimeEnd();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getSendDensityChunks();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getSimObjIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.sim.SimObjRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional double sim_time_start = 1;
 * @return {number}
 */
proto.sim.SimDataRequest.prototype.getSimTimeStart = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sim.SimDataRequest} returns this
 */
proto.sim.SimDataRequest.prototype.setSimTimeStart = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double sim_time_end = 2;
 * @return {number}
 */
proto.sim.SimDataRequest.prototype.getSimTimeEnd = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sim.SimDataRequest} returns this
 */
proto.sim.SimDataRequest.prototype.setSimTimeEnd = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional bool send_density_chunks = 3;
 * @return {boolean}
 */
proto.sim.SimDataRequest.prototype.getSendDensityChunks = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sim.SimDataRequest} returns this
 */
proto.sim.SimDataRequest.prototype.setSendDensityChunks = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated SimObjRequest sim_obj_ids = 4;
 * @return {!Array<!proto.sim.SimObjRequest>}
 */
proto.sim.SimDataRequest.prototype.getSimObjIdsList = function() {
  return /** @type{!Array<!proto.sim.SimObjRequest>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sim.SimObjRequest, 4));
};


/**
 * @param {!Array<!proto.sim.SimObjRequest>} value
 * @return {!proto.sim.SimDataRequest} returns this
*/
proto.sim.SimDataRequest.prototype.setSimObjIdsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.sim.SimObjRequest=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sim.SimObjRequest}
 */
proto.sim.SimDataRequest.prototype.addSimObjIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.sim.SimObjRequest, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sim.SimDataRequest} returns this
 */
proto.sim.SimDataRequest.prototype.clearSimObjIdsList = function() {
  return this.setSimObjIdsList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sim.SimRequest.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.sim.SimRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  SIM_DATA_REQUEST: 1
};

/**
 * @return {proto.sim.SimRequest.RequestCase}
 */
proto.sim.SimRequest.prototype.getRequestCase = function() {
  return /** @type {proto.sim.SimRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.sim.SimRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sim.SimRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.sim.SimRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sim.SimRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    simDataRequest: (f = msg.getSimDataRequest()) && proto.sim.SimDataRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sim.SimRequest}
 */
proto.sim.SimRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sim.SimRequest;
  return proto.sim.SimRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sim.SimRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sim.SimRequest}
 */
proto.sim.SimRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sim.SimDataRequest;
      reader.readMessage(value,proto.sim.SimDataRequest.deserializeBinaryFromReader);
      msg.setSimDataRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sim.SimRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sim.SimRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sim.SimRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sim.SimRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSimDataRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sim.SimDataRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional SimDataRequest sim_data_request = 1;
 * @return {?proto.sim.SimDataRequest}
 */
proto.sim.SimRequest.prototype.getSimDataRequest = function() {
  return /** @type{?proto.sim.SimDataRequest} */ (
    jspb.Message.getWrapperField(this, proto.sim.SimDataRequest, 1));
};


/**
 * @param {?proto.sim.SimDataRequest|undefined} value
 * @return {!proto.sim.SimRequest} returns this
*/
proto.sim.SimRequest.prototype.setSimDataRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.sim.SimRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sim.SimRequest} returns this
 */
proto.sim.SimRequest.prototype.clearSimDataRequest = function() {
  return this.setSimDataRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sim.SimRequest.prototype.hasSimDataRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * @enum {number}
 */
proto.sim.SolarObj = {
  SUN: 0,
  EARTH: 1,
  MOON: 2
};

goog.object.extend(exports, proto.sim);
