[package]
name = "pose_web"
version = "0.1.0"
authors = ["Dylan R. Wagner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5.0"
actix = "0.10"
actix-web = "3"
actix-web-actors = "3"